logrus:
  # 日志级别（默认debug）
  level: debug
  # 是否输出基本信息（默认true）
  printBasic: true

gin:
  # Gin的模式（默认: debug，可选值: debug|release|test）
  mode: debug
  # 一般情况下，用""就够了
  #  hostName: "::1"
  # http server使用的端口（默认0: 不使用http server）
  port: 80
  # 禁用日志带颜色输出?（默认: false）
  disableColor: false
  # 是否开启pprof路由？（默认: false）
  # PS: 只应该在性能测试的时候才在代码中引入pprof.
  pprof: false
  #  ssl:
  #    # https server使用的端口（默认0: 不使用https server）
  #    port: 443
  #    # 证书文件(建议 .pem || .crt)
  #    certFile: _chimera-lib/ssl.crt
  #    # key文件(".key"后缀)
  #    keyFile: _chimera-lib/ssl.key
  middleware:
    gzip:
      # gzip的压缩级别
      #   gzip.HuffmanOnly			  -2	仅使用 Huffman 编码，不做 LZ77 匹配，速度极快但压缩率低
      #   gzip.DefaultCompression	  -1	默认压缩级别（推荐，平衡速度与压缩率）（对应的实际级别是 6）
      #   gzip.NoCompression		  0		不压缩（仅封装 gzip 格式，无实际压缩）
      #   gzip.BestSpeed			  1		最快速度，压缩率最低
      #   2~8						  2~8   中间级别，数字越大压缩率越高、速度越慢
      #   gzip.BestCompression		  9		最高压缩率，速度最慢
      level: -1
      # 单位: bytes
      # <=0: 所有响应都压缩（CPU浪费明显、小文件收益极低）
      # 为什么通常选 1k（1024 字节）？
      #   小于 1KB 的响应：压缩收益很小（甚至可能更大），但 CPU 仍然要付出压缩开销
      #   大于 1KB：压缩收益明显（HTML / JSON / CSS / JS）
      minLength: 1024
      excludedExtensions: [ ".png", ".gif", ".jpeg", ".jpg", ".webp" ]
      # e.g.
      # 配置为 "/api.do"，(1) 能通过: http://127.0.0.1/api.do
      #                  (2) 不能通过: http://127.0.0.1/g/api.do
      excludedPaths:
      # e.g.
      # 配置为 "(.*)/api.do"，能通过: http://127.0.0.1/api.do、http://127.0.0.1/g/api.do
      excludedPathsRegexps:
    # 全局对request body的大小限制（整数; 单位: MB; 默认: 0; <=0: 不做限制; >0: 进行限制）
    # 不建议在此处配置，想限制上传文件大小可以在handler中进行处理
    # TODO: 因为http.MaxBytesReader()，如果涉及"请求转发（代理）"，转发方不要全局配置此属性，否则会导致: 有时成功，有时代理失败（error），有时http客户端失败
    bodyLimit: -1
    # 启用cors的情况下，如果请求头中Origin为空（即非跨域请求），do nothing
    cors:
      # 是否配置cors？默认: false（此时下面的 origins配置 将无效）
      access: true
      # true: 	设置响应头 "Access-Control-Allow-Credentials" 为 "true"
      #	false:	do nothing
      allowCredentials: true
      # 支持的Origin(s)，即响应头中的Access-Control-Allow-Origin
      # (1) 默认（origins配置项全注释了）: 支持所有的Origin（即动态支持请求的Origin，并非"*"）
      # (2) 支持域名匹配
      origins:
        - "*.baidu.com"
    #        - "https://*.baidu.com"
    #        - "https://*.baidu.com"
    #        - "https://*.github.com"
    #        - "https://facebook.com"
    #        - "http://192.168.9.141:8080"
    # 限流器（令牌桶算法）
    rateLimiter:
      # 每秒生成的令牌数
      r: 1000
      # 令牌桶的容量
      b: 2000
    # 额外设置的响应头
    responseHeaders:
      X-XSS-Protection: "1;mode=block"
      Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"

redis:
  # key的前缀（默认: ""）
  # 此处配置项仅用于方便在代码中获取，真正实现得靠业务自己（go-redis不支持），否则可能会有问题，详见下例.
  # e.g. A服务和B服务都有不同的前缀，A写入数据，B读取数据，可能会导致: B读取不到数据，因为B读取时会加上B的前缀.
  keyPrefix:
  userName:
  # 如果Redis有密码，此处配置必须配置
  # 如果Redis无密码，此处配置配不配置皆可（配置了也不会报错）
  password:
  # Redis集群模式
  #   single:       单点
  #   masterSlave:  主从集群（暂不支持）
  #   sentinel:     哨兵集群
  #   cluster:      cluster集群
  mode: single
  single:
    addr: 127.0.0.1:6379
    #    addr: 172.18.21.11:51002
    #    addr: 172.18.21.11:6380
    db: 0
  sentinel:
    addrs:
      - 172.18.21.17:26380
      - 172.18.21.17:26381
      - 172.18.21.17:26382
    masterName: mymaster
    db: 0
  cluster:
    # true: use replicas for read operations
    # 建议设置为false: 这有助于保持整体逻辑清晰，即所有读、写操作都直接发送到主节点，而不会由于意外的读取配置而间接导致写入从节点(只读)。
    useReplicasForReadOperations: false
    # 二选一:
    # (1) 所有的主节点（master），推荐
    # (2) 所有的主节点（master） + 所有的从节点（slave）
    addrs:
      - 192.168.80.27:7001
      - 192.168.80.43:7005
      - 192.168.80.42:7003
pulsar:
  addrs:
    - 127.0.0.1:6650

etcd:
  endpoints:
    - 127.0.0.1:2379

rocketmq5:
  endpoints:
    - 127.0.0.1:8081
#    - 192.168.80.51:28888
#    - 192.168.80.90:28888
#  credentials:
#    accessKey:
#    accessSecret:
#    securityToken:

mysql:
  userName: root
  password: ~Test123
  host: 127.0.0.1:3306
  dbName: ccc2
  pool:
    # set the maximum number of connections in the idle connection pool
    MaxIdleConns: 32
    # set the maximum number of open connections to the database
    MaxOpenConns: 128
    # set the maximum amount of time a connection may be reused
    ConnMaxLifetime: 30m

nacos:
  # 本服务默认的命名空间的id，配置 "" 和 "public" 效果一样（都是使用保留空间public）
  # !!!: 是 id 不是 name.
  #  namespaceId: e7015be0-3947-4050-a411-21705f15e051
  # Nacos服务器的地址
  addrs:
    - http://localhost:8848/nacos
